// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HastPiControl.Adafruit.v2.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class BlockFeed
    {
        /// <summary>
        /// Initializes a new instance of the BlockFeed class.
        /// </summary>
        public BlockFeed() { }

        /// <summary>
        /// Initializes a new instance of the BlockFeed class.
        /// </summary>
        public BlockFeed(string id = default(string), Feed feed = default(Feed), Group group = default(Group))
        {
            Id = id;
            Feed = feed;
            Group = group;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "feed")]
        public Feed Feed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "group")]
        public Group Group { get; set; }

    }
}
