// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HastPiControl.Adafruit.v2.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class BlockBlockFeedsItem
    {
        /// <summary>
        /// Initializes a new instance of the BlockBlockFeedsItem class.
        /// </summary>
        public BlockBlockFeedsItem() { }

        /// <summary>
        /// Initializes a new instance of the BlockBlockFeedsItem class.
        /// </summary>
        public BlockBlockFeedsItem(string feedId = default(string), string groupId = default(string))
        {
            FeedId = feedId;
            GroupId = groupId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "feed_id")]
        public string FeedId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "group_id")]
        public string GroupId { get; set; }

    }
}
