// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HastPiControl.Adafruit.v2.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Additional details about this feed.
    /// </summary>
    public partial class FeedDetails
    {
        /// <summary>
        /// Initializes a new instance of the FeedDetails class.
        /// </summary>
        public FeedDetails() { }

        /// <summary>
        /// Initializes a new instance of the FeedDetails class.
        /// </summary>
        public FeedDetails(IList<object> sharedWith = default(IList<object>), FeedDetailsData data = default(FeedDetailsData))
        {
            SharedWith = sharedWith;
            Data = data;
        }

        /// <summary>
        /// Access control list for this feed
        /// </summary>
        [JsonProperty(PropertyName = "shared_with")]
        public IList<object> SharedWith { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "data")]
        public FeedDetailsData Data { get; set; }

    }
}
