// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HastPiControl.Adafruit.v2.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FeedDetailsData
    {
        /// <summary>
        /// Initializes a new instance of the FeedDetailsData class.
        /// </summary>
        public FeedDetailsData() { }

        /// <summary>
        /// Initializes a new instance of the FeedDetailsData class.
        /// </summary>
        public FeedDetailsData(IDictionary<string, Data> first = default(IDictionary<string, Data>), IDictionary<string, Data> last = default(IDictionary<string, Data>), int? count = default(int?))
        {
            First = first;
            Last = last;
            Count = count;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "first")]
        public IDictionary<string, Data> First { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "last")]
        public IDictionary<string, Data> Last { get; set; }

        /// <summary>
        /// Number of data points stored by this feed.
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public int? Count { get; set; }

    }
}
