// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HastPiControl.Adafruit.v2.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Permission
    {
        /// <summary>
        /// Initializes a new instance of the Permission class.
        /// </summary>
        public Permission() { }

        /// <summary>
        /// Initializes a new instance of the Permission class.
        /// </summary>
        public Permission(string mode = default(string), string scope = default(string), string scopeValue = default(string))
        {
            Mode = mode;
            Scope = scope;
            ScopeValue = scopeValue;
        }

        /// <summary>
        /// Possible values include: 'r', 'w', 'rw'
        /// </summary>
        [JsonProperty(PropertyName = "mode")]
        public string Mode { get; set; }

        /// <summary>
        /// Possible values include: 'secret', 'public', 'user', 'organization'
        /// </summary>
        [JsonProperty(PropertyName = "scope")]
        public string Scope { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "scope_value")]
        public string ScopeValue { get; set; }

    }
}
