// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HastPiControl.Adafruit.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Feed
    {
        /// <summary>
        /// Initializes a new instance of the Feed class.
        /// </summary>
        public Feed() { }

        /// <summary>
        /// Initializes a new instance of the Feed class.
        /// </summary>
        public Feed(string name = default(string), string key = default(string), string description = default(string), string unitType = default(string), string unitSymbol = default(string), string visibility = default(string), string license = default(string), string groupId = default(string), bool? history = default(bool?))
        {
            Name = name;
            Key = key;
            Description = description;
            UnitType = unitType;
            UnitSymbol = unitSymbol;
            Visibility = visibility;
            License = license;
            GroupId = groupId;
            History = history;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "key")]
        public string Key { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unit_type")]
        public string UnitType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unit_symbol")]
        public string UnitSymbol { get; set; }

        /// <summary>
        /// Possible values include: 'private', 'public'
        /// </summary>
        [JsonProperty(PropertyName = "visibility")]
        public string Visibility { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "license")]
        public string License { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "group_id")]
        public string GroupId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "history")]
        public bool? History { get; set; }

    }
}
